import '../styles/global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <meta name='viewport' content='width=device-width, initial-scale=1.0'></meta>
      <body>
        {children}
      </body>
    </html>
  )
}
